/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JavaFileExtractor;

public class Main {
    /*
    Input: 1) Project Path, 2) File name extension, 3) output path
    (Example) ./deeplearning4j java ./deeplearning4j_files.txt
     */
    public static void main(String[] args){
        String projectPath = args[0];
        String extension = args[1];
        String outputPath = args[2];
        JavaFileExtractor e = new JavaFileExtractor();
        e.extract(projectPath, extension, outputPath);
    }
}
